spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:9001
          predicates:
            - Path=${service.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:9002
          predicates:
            - Path=${service.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${service.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${service.api-prefix}/post/**
          filters:
            - StripPrefix=2
server:
  port: 9000
service:
  api-prefix: /api/v1