server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/post-service?authSource=admin
